name: Run Kotlin Hello World Script

on:
  push:
    branches:
      - aprendiendo-github-actions
  workflow_dispatch: 

jobs:
  build-and-run:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Set up JDK 17
      uses: actions/setup-java@v4 
      with:
        java-version: '17' 
        distribution: 'temurin' 

    - name: Download Kotlin Compiler
      run: |
        KOTLIN_VERSION="1.9.23" 
        wget https://github.com/JetBrains/kotlin/releases/download/v${KOTLIN_VERSION}/kotlin-compiler-${KOTLIN_VERSION}.zip
        unzip kotlin-compiler-${KOTLIN_VERSION}.zip -d kotlin-compiler
        echo "$PWD/kotlin-compiler/bin" >> $GITHUB_PATH 

    - name: Compile Kotlin Script
      run: |
        kotlinc HolaMundo.kt -include-runtime -d hello-world.jar # Compila el script en un JAR ejecutable

    - name: Run Kotlin Script
      run: |
        java -jar hello-world.jar
